import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Blogs | Home</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=' bg-slate-50'>
        <Link href={"/blogs"}>Click here to redirect to Blogs page!</Link>
      </main>
    </>
  );
}
